version: "3.8"
services:
  database:
    container_name: pr-database
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
